version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secretpassword}
      POSTGRES_DB: ${DB_NAME:-inventory_mgmt}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: inventory_api
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-secretpassword}@postgres_db:5432/${DB_NAME:-inventory_mgmt}
      # Defaults to localhost, but can be overridden by an environment variable
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        # This is to injects the API endpoint during the Docker build stage
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    container_name: inventory_ui
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
